### ISSUE TITLE
.addCc("email@domian.com) not sending mail 

### ISSUE THREAD

**Issue by jtkinser** [sendgrid/sendgrid-nodejs#162]
When using .addCc("email@domain.com), the email is never actually sent to the CC address. However it is listed in the email CC field on the email that is sent to the .addTo() recipient.

**Comment by eddiezane** [comment]
There is a breaking change that needs to be implemented in this library that will default to using our Web API parameters as opposed to currently using the SMTP API Header for `to` email addresses. The SMTP API Header does not support `cc` or `bcc` addresses.

A fix for the time being is to explicitly use the Web API parameters:

```javascript
email.to = ['foo@example.com', 'bar@example.com'];
email.addCc('baz@example.com'); // same as email.cc = 'baz@example.com'
```

Appologies for the confusion.

**Comment by juanpgaviria** [comment]
Hi,

I have the same issue with cc and bcc, i try with email.cc and email.addCc and no email its sent to the cc addres..

**Comment by eddiezane** [comment]
Hi @juanpgaviria,

I just confirmed that it does indeed work with these methods.

```javascript
var sg = require('sendgrid')(process.env.SENDGRID_APIKEY);

var email = new sg.Email();

email.to = 'foo@example.com';
email.subject = 'Testing CC + BCC';
email.from = 'me@example.com';
email.text = 'Testing';
email.addCc('bar@example.com');
email.bcc = 'baz@example.com';

sg.send(email, function(err, json) {
  if (err) console.error(err);
  console.log(json);
});
```

Please test with the latest version of the library and share a code sample if it still doesn't work.

**Comment by juanpgaviria** [comment]
@eddiezane 

it works.. i was adding the bcc as array.. i think that the issue.. after 3 jack daniel's anything can happend.

thanks ;).

**Comment by eddiezane** [comment]
Haha no worries! I realized that we were missing `addBcc` and `setBccs` so I just released a new version - 1.8.0 with them.

**Comment by jcksncllwy** [comment]
Hi there! I believe I may have found a related bug. If email.addTo("foo@example.com") is called before email.addCc('bar@example.com') then the cc email is not sent.

```
var sg = require('sendgrid')(process.env.SENDGRID_APIKEY);

var email = new sg.Email();

email.addTo('foo@example.com');
email.subject = 'Testing CC + BCC';
email.from = 'me@example.com';
email.text = 'Testing';
email.addCc('bar@example.com');
email.bcc = 'baz@example.com';

sg.send(email, function(err, json) {
  if (err) console.error(err);
  console.log(json);
});
```

**Comment by vinhtq** [comment]
I have the same problem, cannot send email to bcc or cc email address!
Does anybody have solution?

**Comment by vinhtq** [comment]
One more problem, i try to to as @eddiezane way and it works but in the cc or bcc the substitution not working! Only body content display!

**Comment by jacquesgingras** [comment]
I am still having this issue as well. Whether I add the cc using setCcs or addCc, it displays in the email that the To recipient receives, but the recipient in the CC address doesn't receive it.

**Comment by kunal732** [comment]
@jacquesgingras, @ohhdear, @mbernier @tushdante   Looking into this right now. It appears that when the to field is set in the x-smtpapi header, it ignores the cc param. If we just set "to" using the WEB API params, cc works fine.

**Comment by mbernier** [comment]
@kunal732 @tushdante we'll get this prioritized in the backlog to get it taken care of. 

Thanks!

**Comment by hsalazr** [comment]
yep i had the same issue. with "sendgrid": "^**1.9.2**",

**This way just send "to" and ignores "bcc"**
```
email.addBcc('samplecopy@mail.com');
email.addTo('sample@mail.com');
```
**This way send to both**
```
email.bcc ='samplecopy@mail.com';
email.to = 'sample@mail.com';
```

so "it works" :)
